apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::251620885594:role/eks-NodeInstanceRole-1TOUD5RY03QEN
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
# ------------------------------------------Important commands-------------------------
#aws eks update-kubeconfig --name nginx
#kubectl apply -f blue.yml
#kubectl delete deploy/web-deployment-blue svc/webapp-service