apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue
  labels:
    app: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blue
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
      - name: devops-blue-deployment
        image: sshukla30/capstone:latest
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: blue
spec:
  selector:
    app: blue
  ports:
  - protocol: TCP
    port: 80
  type: LoadBalancer
---