apiVersion: apps/v1
kind: Deployment
metadata:
  name: green
  labels:
    app: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: green
  template:
    metadata:
      labels:
        app: green
    spec:
      containers:
      - name: devops-green-deployment
        image: sshukla30/capstone:latest
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: green
spec:
  selector:
    app: green
  ports:
  - protocol: TCP
    port: 80
  type: LoadBalancer
---